### ISSUE TITLE
Orange Pi Pc support

### ISSUE THREAD

**Issue by trohnjavolta** [ludiazv/octocitrico#2]
Hi, as discussed via pm I'm opening this request to ask for Orange Pi Pc support.
I have the device and can test the image for proper configuration, if I get the a list of things/commands to check.
Thx in advance for the effort!

**Comment by ludiazv** [comment]
Hi,
   I compiled a 1st version for you to check. I will upload now upon releases a test version.

Check list:
- Check octo print. I think the best way is printing something. 
- Check if all usb ports work. e.g. plug a usb drive and test with lsblk
- Check if console over USB-OTG works.
- Check if uart is enabled: ls -l /dev/tty*
- Check if spidev i enabled: ls -l /dev/spi*
- Check if i2c is enabled: ls -l /dev/i2c*
- Check smb access to pi files in your board. You need to activate the service first using ``scripts/citrico-config``
If you are able to test the a usb webcam do it.

**Comment by trohnjavolta** [comment]
Hi, bad news: I cannot geht the OPiPc to boot at all with the image :(
Balena Etcher doesn't even want to flash it in the first place..
Draging the file into etcher, etcher tells me:
"It looks like this is not a bootable image. The image does not appear to contain a partition table, and might not be recognized or bootable by your device."

I still can flash the sd card but after inserting it in the OPiPc and powering it on, it does not show up on my network and trying to ssh with the ip or hostname (I bound the mac address to a ip adress on my router) I get a timeout.
I cannot rule out that I'm doing sth. wrong here..but I already flashed many images and booted many. I don't see doins sth. wrong here.

**Comment by trohnjavolta** [comment]
Whoops, I didn't want to close it..how can I revert this? :O

**Comment by ludiazv** [comment]
Hi,
   I can't test on the opiPC as I don't have this board. But I unpacked the image and flashed with etcher without any warning or message.  The img files is 2.21GB. I've mounted the SD in my linux box and a 2.1G root file system exists with the propper files.

Did you check sha256 image with the sha signature in the pacakge?

**Comment by trohnjavolta** [comment]
That's strange..maybe my sd cards are messed up. I'll try again in linux using dd.

**Comment by ludiazv** [comment]
To discard any hw or power issues I would recommend to boot the board with a fresh image of armbian for opi pc from the page. 

Using a monitor + keyboard or if you have one a serial console (usb<-->ttl) to check the boot process. 
If the board boot ok. Then try with the img I uploaded with the same SD card.

**Comment by trohnjavolta** [comment]
Alright, so booting the image works, I messed sth. up in the first place.
Also everything else seems to work:
Octoprint works, I successfully printed sth.
All usb ports work fine
uart devices show up
spidev shows up 
i2c shows up
and pi-files smb share is also accessable.

Only think I couldn't get to work is console over usb otg...but I never used that before so I probably did sth. wrong here.

Again, thx for compiling this for the Orange Pi Pc!

**Comment by ludiazv** [comment]
Nice. OTG is a nice to have, especially in this board that has ethernet. Console over otg is important on wifi-only boards as network need to be configured logging into the system.

I close this issue. You are gonging to start working with GPIOS. Have in mind that using not root users you need to insert udev rules.
