### ISSUE TITLE
octocitrico with on board camera interface ("raspi camera") not working

### ISSUE THREAD

**Issue by shaise** [ludiazv/octocitrico#34]
Does anyone know if citrico on banana pi m2 zero works with "raspi" camera?
Checking mjpg_streamer directory, i cant find `input_raspi.so`
Trying to recompile mjpg_streamer I get:  

```
 The following features have been disabled:  
 * PLUGIN_INPUT_RASPICAM, Raspberry Pi input camera plugin (unmet dependencies)
```

Thanks!

**Comment by ludiazv** [comment]
Never tried but I think it wont be easy to make it work as streamer service in octopi with raspi cam is configured to work in Raspi not in other ARM boards.

My recomendation is to go with USB camera as they should be "universal".

**Comment by shaise** [comment]
Thanks!
This is very helpful.
