### ISSUE TITLE
Issues getting webcam to work on OrangePi 3 LTS.

### ISSUE THREAD

**Issue by murmlei** [ludiazv/octocitrico#36]
Hello,

I am trying to get the webcam/timelapse to work on an OrangePi 3 LTS, I am using a Logitech C920.

I am unable to turn the WebCam Streamer on by using sudo scripts/citrico-config. 

I have modified octopi.txt as follows:
camera="usb"
camera_usb_option="-r 1920x1080 -f 30"
All other options I have left untouched.

I have also ran the commands from this comment:
https://github.com/ludiazv/octocitrico/issues/9#issuecomment-792071920

Despite all of this, OctoPrint says the webcam server is currently not running.

Attached are screenshots of other troubleshooting I have done. Any help regarding this is appreciated and please ask me to provide any additional information you need. Either way a big thank you for creating the boot image.
![webcam1](https://user-images.githubusercontent.com/16343458/214128189-caeb652e-8cdf-4eb4-a378-b496c4ed26c4.PNG)
![webcam2](https://user-images.githubusercontent.com/16343458/214128191-ab15797b-116f-4bc6-ac8e-58b95d48da05.PNG)
![webcam3](https://user-images.githubusercontent.com/16343458/214128192-f792dfee-dcb9-44c8-b9be-789b78ec7f05.PNG)

**Comment by ludiazv** [comment]
WebCam service changed with in recent versions of octopi. Commands in #9 are not sufficient now. Another server must be started  ```streamer_select.service```.   Run ``pi/scripts/citrico-config`` and enable webcam service and reboot. This service will on every boot active webcamd or hls_streamer (experimental) on each boot based on the configuration file.

A quick fix is also to create the file that webcamd service needs to start:
``sudo touch /etc/octopi_streamer/mjpeg``

**Comment by murmlei** [comment]
Thank you for the advice. For some reason I can't figure out how to turn on the streamer_select.service through the citrico-config. Any navigational key I hit just changes between the listed items or 'OK' and 'Cancel', pressing enter just turns on all the features already turned on.

With the `sudo touch /etc/octopi_streamer/mjpeg` I get a 'cannot touch '/etc/octopi_streamer/mjpeg': No such file or directory.

**Comment by ludiazv** [comment]
does ``/etc/octopi_streamer`` directory exists?  Create it if not and then run the touch command

**Comment by murmlei** [comment]
I created the /etc/octopi_streamer directory and ran the touch command, but still in OctoPrint I'm getting an error of the server not running.

**Comment by murmlei** [comment]
I have managed to start the service, which I can confirm from the citrico-config tool. Unfortunately the webcam is still not showing up.

**Comment by ludiazv** [comment]
Can you provide the logs of webcamd.service? Is this service enabled?

Also check #11. As in some cases you have to modify ``boot.txt`` with correct video device with the option ``-d`` in ``camera_usb_option``

**Comment by murmlei** [comment]
It works now!

I looked at the webcam.service logs and it seemed like it was trying to find the camera in the wrong place.

Changing `camera_usb_options="-d /dev/video1 -r 1920x1080 -f 30"` in octopi.txt seemed to make it work now.

Thank you very much for all your help!
