### ISSUE TITLE
There is not enough free disk space available to run an update

### ISSUE THREAD

**Issue by yo3gts** [ludiazv/octocitrico#4]
Hi, thank you for the help. I manage to install, but now I have another problem:
There is not enough free disk space available to run an update:
 To reduce the likelihood of running into update problems due to insuffient disk space, OctoPrint requires a minimum of 150.0MB free disk space in various locations:

    Python package installation folder (/home/pi/oprint/lib/python2.7/site-packages): 5.4GB free
    Plugin folder (/home/pi/.octoprint/plugins): 5.4GB free
    System temporary files (/tmp): 107.0MB free
I looking in FAQ, and I don't find any clue
Thank you

**Comment by ludiazv** [comment]
Hi,
What board are you using?
Did you tried to reboot before update to clean tmp fs?
what is the result of ``df -h``?
what's inside tmp?

**Comment by yo3gts** [comment]
Hi, it's same after reboot How to clean tmp fs?

root@citrico-opizero:~# df -h
Filesystem      Size  Used Avail Use% Mounted on
udev             50M     0   50M   0% /dev
tmpfs            24M  1.5M   23M   7% /run
/dev/mmcblk0p1  7.2G  1.7G  5.4G  25% /
tmpfs           120M     0  120M   0% /dev/shm
tmpfs           5.0M     0  5.0M   0% /run/lock
tmpfs           120M     0  120M   0% /sys/fs/cgroup
tmpfs           120M  4.0K  120M   1% /tmp
/dev/zram0       49M  1.9M   44M   5% /var/log
tmpfs            24M     0   24M   0% /run/user/0

**Comment by ludiazv** [comment]
I see. Using 256Mb board is not recommended due to low memory but if you do not use webcam and disable plugins it's possible to run octoprint in this limited board but it could become unstable. My recommendation is to go with the 512Mb version of the opizero.

The reason your system is showing /tmp as 120Mb is that by default linux takes for this file system 1/2 of available memory. This can be changed via command line, this will not be permanent on next reboot you would get 120Mb again:
````
# mount -o remount,size=<new size>,noatime /tmp
````

**Comment by yo3gts** [comment]
I managed in the end, I deleted some plugins
it works well, only the temperature is a bit high
[https://1drv.ms/u/s!AqWK3kOa67t0j4tj1BDq-j6pynmPvQ?e=iWwBOo ](url)

**Comment by ludiazv** [comment]
This board is famous for it's high temperature and also there are issues in armbian to report the correct temperature. Depends on the revision of the board. New LTS version claim to have better thermal performance. I have one printer with a opizero LTS 512Mb and the temperatures reported are wrong but it do not overheat much really when I measure the SoC chip externally. I have only a small heatsink an it never failed printing.

It seems, however, this SoC tolerates high temperatures well. I would recommend to use a big heatsink and a 5V fan if the temperature is becoming a issue. At the end this is a <$10 board so if something goes wrong you can allways change it.
