### ISSUE TITLE
Does this work on OPI PC+?

### ISSUE THREAD

**Issue by catallo** [ludiazv/octocitrico#6]
... and if so, is it possible to install it on the internal 8GB eMMC?

**Comment by ludiazv** [comment]
Hi,
   As OPI PC+ is supported by armbian its likely that an image can be build for this board. Now there is no prebuild image for this board in the release section but you can build your own. If can't I could build it for you in the next comming release if you are willing to test it.

As regards eMMC. Armbian provide helper scripts to move your SD card to the internal eMMC. So it would be also possible. The only limitation is maybe the 8G. The image is arround 2-3G but Octoprint typically saves logs and gcodes as you print and eventually you could have storage problems.

**Comment by catallo** [comment]
If you could build an image for the next release that would be great. I'll test it and report.

About the 8GB eMMC, I think I'll just try to write log files and gcodes to an USB drive or SD card.

**Comment by ludiazv** [comment]
Hi @catallo ,
   New release is pusblished. I included a orange PI PC+ prebuild image. If you can test it please send over feedback.

;)

**Comment by catallo** [comment]
I just tried it out and can confirm that it works. 

After booting from SD card I logged in via SSH and used armbian-config to install it on the eMMC. I then removed the SD card and booted from eMMC, configured Wifi using armbian-config and run the wizard using the Web interface.

I successfully run a few test prints using the Octoprint plugin for Cura. I also had to install an extra plugin for Octoprint being able to parse my Ender 3 Pro's faulty temperature reporting. I did that using the built in Plugin-Manager.

The only thing that didn't work for me yet is my Logitech USB webcam but I think I'll figure that out.

TY again for your work on this @ludiazv!

**Comment by ludiazv** [comment]
Great news.
  Have in mind that in order to use the webcam you need to configure cam in /boot/octopi.txt and enable the webcam service (is off in the default configuration)

Regards,

**Comment by catallo** [comment]
Yes, I did that. The problem was mjpg-streamer trying to input from /dev/video0 while my (only) camera was on /dev/video1.

So I added -d /dev/video1 to camera_usb_options in octopi.txt to make it work.

**Comment by ludiazv** [comment]
Great! ;)
before closing this could you check the status of i2c,spidev & gpios.
```bash
$ ls -l /dev/i2c*
$ ls -l /dev/spi*
$ ls -l /sys/class/gpio
´´´

**Comment by catallo** [comment]
`root@citrico-opipcplus:~# ls -l /dev/i2c*
crw-rw---- 1 root i2c 89, 0 Dec 28 15:39 /dev/i2c-0
crw-rw---- 1 root i2c 89, 1 Dec 28 15:39 /dev/i2c-1
crw-rw---- 1 root i2c 89, 2 Dec 28 15:39 /dev/i2c-2`

`root@citrico-opipcplus:~# ls -l /dev/spi*
crw-rw---- 1 root spi 153, 0 Dec 28 15:39 /dev/spidev0.0`

`root@citrico-opipcplus:~# ls -l /sys/class/gpio
total 0
--w--w---- 1 root gpio 4096 Dec 28 15:39 export
lrwxrwxrwx 1 root gpio    0 Dec 28 15:39 gpiochip0 -> ../../devices/platform/soc/1c20800.pinctrl/gpio/gpiochip0
lrwxrwxrwx 1 root gpio    0 Dec 28 15:39 gpiochip352 -> ../../devices/platform/soc/1f02c00.pinctrl/gpio/gpiochip352
--w--w---- 1 root gpio 4096 Dec 28 15:39 unexport`
