### ISSUE TITLE
OrangePi Lite support

### ISSUE THREAD

**Issue by Corgano** [ludiazv/octocitrico#7]
Requesting support for the Orangepi Lite. It's basicly an OrangePi One but with wifi and no ethernet, so it shouldn't be too out there to get support working. I'd be happy to help test it on my orange pi lite board.

**Comment by ludiazv** [comment]
Hi,
  I will try to include this board soon. I let you know.

Happy new year!

**Comment by Corgano** [comment]
Right now imma try the orange pi one image. Who knows might get it working

**Comment by Corgano** [comment]
I tried the orange pi one build, and it seems to work just fine - but doesn't see the wifi module and seems to think it has ethernet. Makes sense given this was the setup of the orange pi one, but was kinda hoping it would detect the wifi and get basic connectivity functioning. Awwe well

**Comment by ludiazv** [comment]
that is expected as the device tree for both boards will be similar but not the same.

**Comment by ludiazv** [comment]
This board has been added in last release today.

**Comment by Corgano** [comment]
Awesome thankyou
