### ISSUE TITLE
webcam doesn't work after reboot

### ISSUE THREAD

**Issue by IvanPanchak** [ludiazv/octocitrico#8]
helo, after edit octoprint.txt (camera_usb_options="-r 1280x720 -f 10 -y"), and enabling webcam service i reboot and all work fine? but after next reboot camera dont work. Then i edit octoprint.txt (camera_usb_options="-r VGA-f 10 -y")? rebot and all work, but to next rebot. webcam logitec c310. pls help. I am noob (     webcamd.service start only one time after reboot.

**Comment by ludiazv** [comment]
Hi,
  Could provide some logs on the webcamd.service?

**Comment by IvanPanchak** [comment]
/var/log/webcamd.log , he is not here. where can i look at the log?

**Comment by ludiazv** [comment]
Yes journalctl must show the problem in webcamd. Octoprint will work without this service so octiprint log is not useful here.
I can't see here any error on the webcamd.service. what is the status.

**Comment by IvanPanchak** [comment]
root@citrico-opizero:~# lsusb
Bus 008 Device 001: ID 1d6b:0001 Linux Foundation 1.1 root hub
Bus 005 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 007 Device 001: ID 1d6b:0001 Linux Foundation 1.1 root hub
Bus 004 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 006 Device 001: ID 1d6b:0001 Linux Foundation 1.1 root hub
Bus 003 Device 002: ID 046d:081b Logitech, Inc. Webcam C310
Bus 003 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 002 Device 001: ID 1d6b:0001 Linux Foundation 1.1 root hub
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub

root@citrico-opizero:~# ls -ltrh /dev/video*
crwxrwxrwx 1 root video 81, 2 Feb 17 09:42 /dev/video2
crwxrwxrwx 1 root video 81, 1 Feb 17 09:42 /dev/video0

root@citrico-opizero:~# v4l2-ctl --list-devices
UVC Camera (046d:081b) (usb-1c1b000.usb-1):
        /dev/video0
        /dev/video2
Maybe it works with the wrong camera?

**Comment by IvanPanchak** [comment]
[  OK  ] Started the OctoPi webcam …ith the user specified config.
[  OK  ] Stopped the OctoPi webcam …ith the user specified config.
[FAILED] Failed to start the OctoPi…ith the user specified config.
See 'systemctl status webcamd.service' for details.

I get this when Opi loads

**Comment by IvanPanchak** [comment]
sudo ffmpeg -f v4l2 -pixel_format yuyv422 -s 1280x720 -i /dev/video1 output.wmv

the camera will turn on when I run this command

**Comment by ludiazv** [comment]
have you test manually on which /dev/videoX the camera works? Does it change in every boot?
If not you can provide the "-d /dev/videoX" in octopi.txt in usb parameters this will force the service to use the device. Also set camera="usb" then you avoid the script to test for raspi cams that do not apply in your context.

**Comment by IvanPanchak** [comment]
camera="usb" - I did it before, it didn't work

camera_usb_options="-d /dev/video1 -r 1280x720 -f 10" - did so and the camera began to run with the system , everything worked, very grateful!
